controller_list:
  - name: fake_ur5e_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rev_a1
      - rev_a2
      - rev_a3
      - rev_a4
      - rev_a5
      - rev_a6
  - name: fake_gripper_controller
    joints:
      - rev_grp
initial:  # Define initial robot poses.
  - group: ur5e_arm
    pose: home
  - group: gripper
    pose: open
