controller_list:
  - name: fake_ur5e_arm_controller
    joints:
      - rev_a1
      - rev_a2
      - rev_a3
      - rev_a4
      - rev_a5
      - rev_a6
  - name: fake_gripper_controller
    joints:
      - rev_grp
  - name: fake_gripper2_controller
    joints:
      - robotiq_85_left_knuckle_joint
initial:  # Define initial robot poses.
  - group: ur5e_arm
    pose: home
  - group: gripper
    pose: open
  - group: gripper2
    pose: open