# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ur5e_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rev_a1
    - rev_a2
    - rev_a3
    - rev_a4
    - rev_a5
    - rev_a6
    # - rev_grp
    - robotiq_85_left_knuckle_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur5e_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rev_a1
      - rev_a2
      - rev_a3
      - rev_a4
      - rev_a5
      - rev_a6
  # - name: gripper_controller
  #   action_ns: follow_joint_trajectory
  #   default: True
  #   type: FollowJointTrajectory
  #   joints:
  #     - rev_grp
  - name: gripper2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robotiq_85_left_knuckle_joint

ur5e_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - rev_a1
    - rev_a2
    - rev_a3
    - rev_a4
    - rev_a5
    - rev_a6
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    rev_a1: {trajectory: 0.1, goal: 0.1}
    rev_a1: {trajectory: 0.1, goal: 0.1}
    rev_a3: {trajectory: 0.1, goal: 0.1}
    rev_a4: {trajectory: 0.1, goal: 0.1}
    rev_a5: {trajectory: 0.1, goal: 0.1}
    rev_a6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

# gripper_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - rev_grp
#   constraints:
#     goal_time: 0.6
#     stopped_velocity_tolerance: 0.05
#     rev_grp: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10

gripper2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robotiq_85_left_knuckle_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.1
    robotiq_85_left_knuckle_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10